//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicDisk
    {
        public int id { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public int PublisherId { get; set; }
        public int StylesId { get; set; }
        public int ArtistId { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual Style Style { get; set; }
    }
}
