//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW_Barber_DatebaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveVisit
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int BarberId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Price { get; set; }
        public int Rating { get; set; }
        public string Feedback { get; set; }
        public Nullable<int> ServiceId { get; set; }
    
        public virtual Barber Barber { get; set; }
        public virtual Client Client { get; set; }
        public virtual servicesList servicesList { get; set; }
    }
}
