//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW_Barber_DatebaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarberService
    {
        public int Id { get; set; }
        public int BarberId { get; set; }
        public int ServiceId { get; set; }
    
        public virtual Barber Barber { get; set; }
        public virtual servicesList servicesList { get; set; }
    }
}
