//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW_Barber_DatebaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Barber()
        {
            this.ArchiveVisits = new HashSet<ArchiveVisit>();
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int Id { get; set; }
        public string FIO { get; set; }
        public bool Gender { get; set; }
        public int PhoneNumber { get; set; }
        public string Email { get; set; }
        public System.DateTime Birthday { get; set; }
        public System.DateTime DateAdmission { get; set; }
        public int PostionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchiveVisit> ArchiveVisits { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
