//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW_Barber_DatebaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BarberShopEntities : DbContext
    {
        public BarberShopEntities()
            : base("name=BarberShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArchiveVisit> ArchiveVisits { get; set; }
        public virtual DbSet<Barber> Barbers { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<servicesList> servicesLists { get; set; }
    }
}
