//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW_Barber_DatebaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public int BarberId { get; set; }
        public System.DateTime FreeDate { get; set; }
        public System.TimeSpan FreeTime { get; set; }
    
        public virtual Barber Barber { get; set; }
    }
}
