//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW_25_08_EntityFrawork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int MusicDiskId { get; set; }
        public System.TimeSpan SongTime { get; set; }
        public int StyleId { get; set; }
        public int ArtistId { get; set; }
    }
}
