//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DZ_DatabaseFirst_DBgames
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int GameStyleId { get; set; }
        public string StudioName { get; set; }
        public System.DateTime DateRelease { get; set; }
    
        public virtual GameStyle GameStyle { get; set; }
    }
}
